### ISSUE TITLE
PostCSS plugin 오류

### ISSUE THREAD

**Issue by parksb** [jmchoi1225/Timetable-simple-#2]
webpack에서 자바스크립트 파일에 import된 css를 읽을 때 style-loader랑 css-loader를 사용하는데, `webpack.config.js`에 관련 설정이 잘못되어 있어서 관련 오류가 생기는 것 같아요. 아래처럼 수정해보세요.

**webpack.config.js**
```diff
{
    test: /\.css$/,
-   loaders: ['style', 'css', 'postcss'],
+   loader: 'style-loader!css-loader',
    include:PATHS.app
},
```
위처럼 해도 되고, `loaders: ['style', 'css', 'postcss']`를 `loaders: ['style', 'css']`로 바꿔도 되지 않을까 싶어요. [공식 문서](https://github.com/webpack-contrib/css-loader)에는 배열을 쓰라고 나와있네요.

**webpack.config.js**
```js
{
    test: /\.css$/,
    use: [ 'style-loader', 'css-loader' ]
}
```

**Comment by jmchoi1225** [comment]
진짜 고맙습니다.
